### ISSUE TITLE
Love your styling!

### ISSUE THREAD

**Issue by teenie-quaggard** [FACxBeamery/tech-test-martha#7]
It's nice to see that you have put some thought into your styling!
One thing to remember is to ensure that you have enough color contrast with text. For example the white on pink text could be very hard for someone with contrast issues to read.
![Screen Shot 2019-11-15 at 11 46 23](https://user-images.githubusercontent.com/37771591/68941423-c2f02780-079d-11ea-8aee-d7f1869101db.png)

**Comment by marthaklambert** [comment]
Thanks!! this is fixed now with black text
